<a href="https://colab.research.google.com/github/Nikita-devel/GoIT_Data_Science/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [33]:
#1
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
#2
a_zero = np.zeros((3, 3), dtype=float)
print(a_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
#3
a_rand_z = np.random.randint(1, 11, size=(5, 5))
print(a_rand_z)

[[ 3  4  6  1  7]
 [ 3  9  3  9  3]
 [10  1  8  3  9]
 [ 2  5  4 10  1]
 [ 8 10  6  7  6]]


In [36]:
#4
a_rand_c = np.random.random(size=(5, 5))
print(a_rand_c)

[[0.1765658  0.20854794 0.09653471 0.99238607 0.07035901]
 [0.04881201 0.52288302 0.88591937 0.42222893 0.01955472]
 [0.0302738  0.45677832 0.24280776 0.7202932  0.42840626]
 [0.94560927 0.91797405 0.88652147 0.87486448 0.72080839]
 [0.54096958 0.66549756 0.73551942 0.22537191 0.22606186]]


In [20]:
#5
a_rand = np.random.randint(1, 10, size=(5))
b_rand = np.random.randint(1, 10, size=(5))
print(a_rand)
print(b_rand)
print(a_rand + b_rand)
print(b_rand - a_rand)
print(a_rand * b_rand)

[7 8 2 2 6]
[2 1 7 8 4]
[ 9  9  9 10 10]
[-5 -7  5  6 -2]
[14  8 14 16 24]


In [24]:
#6
a_rand7 = np.random.rand(7)
b_rand7 = np.random.rand(7)
res = np.dot(a_rand7, b_rand7)
print(a_rand7)
print(b_rand7)
print(res)

[0.80643601 0.83849158 0.80840911 0.24675328 0.63471949 0.34999536
 0.34476986]
[0.75360071 0.04179112 0.94193993 0.48727428 0.48593663 0.90732006
 0.14810429]
2.2015347525561264


In [29]:
#7
a_rand22 = np.random.randint(1, 11, size=(2, 2))
b_rand23 = np.random.randint(1, 11, size=(2, 3))
res_ab = np.dot(a_rand22, b_rand23)
print(a_rand22)
print(b_rand23)
print(res_ab)

[[2 9]
 [2 7]]
[[10  9  6]
 [ 8  7  7]]
[[92 81 75]
 [76 67 61]]


In [32]:
#8
or_a = np.random.randint(1, 11, size=(2, 2))
a_inv = np.linalg.inv(or_a)
print(or_a)
print(a_inv)

[[ 2 10]
 [ 8 10]]
[[-0.16666667  0.16666667]
 [ 0.13333333 -0.03333333]]


In [40]:
#9
or44_a = np.random.rand(4, 4)
or44_a_t = or44_a.T
print(or44_a)
print(or44_a_t)

[[0.55167033 0.57870618 0.79870796 0.33391375]
 [0.79920968 0.94501118 0.58429731 0.5321488 ]
 [0.71542002 0.56433833 0.07154574 0.35519732]
 [0.61466735 0.38866901 0.33198667 0.94126096]]
[[0.55167033 0.79920968 0.71542002 0.61466735]
 [0.57870618 0.94501118 0.56433833 0.38866901]
 [0.79870796 0.58429731 0.07154574 0.33198667]
 [0.33391375 0.5321488  0.35519732 0.94126096]]


In [49]:
#10
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[4 9 4 2]
 [3 5 2 5]
 [9 8 4 6]]
[9 4 8 3]
[110  78 163]


In [48]:
#11
a = np.random.rand(2, 3)
b = np.random.rand(3)
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[0.59779502 0.01809146 0.09219456]
 [0.87651822 0.87193095 0.40282601]]
[0.33138597 0.46086005 0.69430278]
[0.27044945 0.9719872 ]


In [50]:
#12
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = a * b
print(a)
print(b)
print(c)

[[8 5]
 [7 4]]
[[6 3]
 [9 1]]
[[48 15]
 [63  4]]


In [51]:
#13
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[ 9  6]
 [ 9 10]]
[[4 5]
 [7 3]]
[[ 78  63]
 [106  75]]


In [55]:
#14
a = np.random.randint(1, 101, size=(5, 5))

print(a)
print(a.sum())

[[58 81 99 86 99]
 [65 58 37 40 38]
 [97 16  4  3 31]
 [28 48 32  9 72]
 [13  1 84  1 26]]
1126


In [56]:
#15
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
c = a - b
print(a)
print(b)
print(c)

[[ 3 10  1  8]
 [ 6  2  9  6]
 [ 1  9 10  5]
 [ 7  9  7  2]]
[[ 6  4  8 10]
 [ 6  5  6  5]
 [ 8  1  3  6]
 [ 6  3  5  7]]
[[-3  6 -7 -2]
 [ 0 -3  3  1]
 [-7  8  7 -1]
 [ 1  6  2 -5]]


In [57]:
#16
a = np.random.rand(3, 3)
column_sum = np.sum(a, axis=1, keepdims=True)
print(a)
print(column_sum)
print(a.sum())

[[0.42274589 0.33788383 0.54694712]
 [0.72785692 0.25338602 0.79924637]
 [0.1851733  0.09456098 0.57203973]]
[[1.30757685]
 [1.78048931]
 [0.85177401]]
3.9398401727729944


 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [59]:
#17
a = np.random.randint(1, 11, size=(3, 4))
square_a = np.square(a)
print(a)
print(square_a)

[[8 3 8 3]
 [8 5 4 9]
 [6 7 2 7]]
[[64  9 64  9]
 [64 25 16 81]
 [36 49  4 49]]


In [60]:
a = np.random.randint(1, 51, size=4)
sqrt_a = np.sqrt(a)
print(a)
print(sqrt_a)

[17  6 15 14]
[4.12310563 2.44948974 3.87298335 3.74165739]
